version: '2'
services:
  spotweb:
    build:
      context: .
      dockerfile: ./x86/Dockerfile
    ports:
     - "8080:80"
    depends_on:
    - "mysql"
  mysql:
    image: "mysql:8"
    volumes:
      - ./mysql:/docker-entrypoint-initdb.d
    environment:
      MYSQL_RANDOM_ROOT_PASSWORD: 'yes'
