version: '3.8'
services:
  spotweb:
   image: erikdevries/spotweb
    ports:
     - "8080:80"
    depends_on:
    - "mysql"
  mysql:
    image: mysql:latest
    environment:
      MYSQL_ROOT_PASSWORD: 123456
      MYSQL_USER: aegp17
      MYSQL_PASSWORD: 123456
      MYSQL_DATABASE: 123456
